// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uybpcbjhkwtmwggvezhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5YnBjYmpoa3d0bXdnZ3Zlemh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzg4MzEsImV4cCI6MjA2NTc1NDgzMX0.XYK018YTEiXtRybLztbXP7WZidRAhgYIiMXRA-6IVds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);